name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: SnakeByte ${{ steps.version.outputs.VERSION }}
        body: |
          ## SnakeByte ${{ steps.version.outputs.VERSION }}
          
          🚀 **Quick Install:**
          ```bash
          curl -sSL https://raw.githubusercontent.com/${{ github.repository }}/main/install.sh | bash
          ```
          
          📥 **Manual Download:**
          Download `snakebyte.py` below and run:
          ```bash
          python snakebyte.py your_binary_file.bin
          ```
          
          ## ✨ Features
          - Interactive hex and ASCII display
          - Multiple character encoding support
          - Search functionality (hex and ASCII)
          - Multiple color schemes
          - Cross-platform compatibility
          - Zero dependencies
          
          ## 📋 Requirements
          - Python 3.6 or later
          - No external dependencies required
          
          ---
          **Full documentation:** [README](https://github.com/${{ github.repository }}/blob/main/README.md)
        files: |
          snakebyte.py
          install.sh
        draft: false
        prerelease: false
