name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Test Python syntax
      run: python -m py_compile snakebyte.py
    
    - name: Verify script exists and is readable
      run: |
        ls -la snakebyte.py
        head -5 snakebyte.py
