name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Test syntax
      run: |
        python -m py_compile snakebyte.py
    
    - name: Create test binary file
      run: |
        python -c "
import struct
with open('test.bin', 'wb') as f:
    f.write(b'Hello World!')
    f.write(struct.pack('<i', 42))
    f.write(b'\x00\x01\x02\x03')
        "
    
    - name: Test basic functionality
      run: |
        timeout 5 python snakebyte.py test.bin < /dev/null || true
      shell: bash
